it:
  prefixes: ["62", "63"]
marketing:
  prefixes: ["73", "70"]
logistics:
  prefixes: ["49", "52"]
retail:
  prefixes: ["47"]
manufacturing:
  prefixes:
    ["10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33"]
other:
  prefixes: []
